"""Phase 3 & Core Logistics App: Operational Entities CRUD & Management.

Manages:
- Trucks (with full Origin, Destination, Driver, Cargo Manifest, Telemetry & Color-Coded Route)
- Containers (ISO 6346, gross/tare weights, seal numbers, 3D bay slots)
- Equipment (RTG Cranes, Reach Stackers, EV AGVs)
- Gate Passes (Issue, Verify, QR token generation)
- Multimodal Schedules (Train Rakes & Vessel Calls)
"""
from datetime import datetime, timedelta
import random
from typing import List, Optional, Dict, Any
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

router = APIRouter(prefix="/api/entities", tags=["logistics-entities"])

INITIAL_TRUCKS = [
    # Corridor 1: SH-176 North Express (Madurai / Chennai / Delhi / Mumbai)
    {
        "id": "TRK-MH-12-8841",
        "license_plate": "MH-12-RN-8841",
        "carrier": "Mahindra Logistics Express (Mumbai)",
        "driver_name": "Rajesh V. Patil",
        "driver_phone": "+91 98220 44912",
        "driver_experience_years": 18,
        "truck_type": "MULTI_AXLE_HEAVY_40FT",
        "status": "INBOUND_HIGHWAY",
        "origin": "Pune-Chakan Auto Cluster (Maharashtra) via NH-44",
        "destination": "MMLP Yard Block A (Export Staging)",
        "cargo_name": "Automotive Transmission Units (Mahindra & Tata)",
        "cargo_type": "AUTO_PARTS",
        "container_no": "MSKU-774190-2",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 28.5,
        "tare_weight_tonnes": 4.1,
        "net_weight_tonnes": 24.4,
        "seal_number": "SL-MH-99412",
        "ewaybill_no": "EWB-2026-MH-991204",
        "latitude": 8.7826,
        "longitude": 78.1405,
        "heading": 175.0,
        "speed_kmh": 48.0,
        "fuel_or_battery_pct": 82.0,
        "eta_minutes": 12.0,
        "eta_timestamp": "14:20 IST",
        "route_color": "#3b82f6",
        "route_type": "HIGHWAY_NORTH_SH176",
        "state_of_origin": "Maharashtra",
        "corridor_id": "CORRIDOR_NORTH_SH176",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-DL-01-9920",
        "license_plate": "DL-01-AB-9920",
        "carrier": "Northern Logistics Express (Delhi-NCR)",
        "driver_name": "Harpreet Singh",
        "driver_phone": "+91 98110 55671",
        "driver_experience_years": 21,
        "truck_type": "LONG_HAUL_HEAVY_TRAILER",
        "status": "INBOUND_HIGHWAY",
        "origin": "Gurugram ICD (Delhi-NCR) via Golden Quadrilateral",
        "destination": "MMLP Yard Block A",
        "cargo_name": "Heavy Industrial Machinery & Robotics",
        "cargo_type": "CAPITAL_GOODS",
        "container_no": "CMAU-551902-8",
        "iso_type": "40OT Open Top",
        "gross_weight_tonnes": 31.4,
        "tare_weight_tonnes": 4.6,
        "net_weight_tonnes": 26.8,
        "seal_number": "SL-DL-88194",
        "ewaybill_no": "EWB-2026-DL-882194",
        "latitude": 8.7790,
        "longitude": 78.1395,
        "heading": 174.0,
        "speed_kmh": 46.0,
        "fuel_or_battery_pct": 68.0,
        "eta_minutes": 9.0,
        "eta_timestamp": "14:17 IST",
        "route_color": "#3b82f6",
        "route_type": "HIGHWAY_NORTH_SH176",
        "state_of_origin": "Delhi",
        "corridor_id": "CORRIDOR_NORTH_SH176",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-AP-03-6612",
        "license_plate": "AP-03-TY-6612",
        "carrier": "Andhra Coastal Logistics Express",
        "driver_name": "B. Venkateswarlu",
        "driver_phone": "+91 98480 33419",
        "driver_experience_years": 11,
        "truck_type": "PRIME_MOVER_40FT",
        "status": "INBOUND_HIGHWAY",
        "origin": "Sri City Industrial SEZ (Andhra Pradesh)",
        "destination": "MMLP Central Warehouse WH-01",
        "cargo_name": "Active Pharmaceutical Ingredients (API) & Medical Devices",
        "cargo_type": "PHARMACEUTICALS",
        "container_no": "TEMU-330194-2",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 22.8,
        "tare_weight_tonnes": 3.9,
        "net_weight_tonnes": 18.9,
        "seal_number": "SL-AP-55102",
        "ewaybill_no": "EWB-2026-AP-339102",
        "latitude": 8.7760,
        "longitude": 78.1382,
        "heading": 172.0,
        "speed_kmh": 45.0,
        "fuel_or_battery_pct": 84.0,
        "eta_minutes": 7.0,
        "eta_timestamp": "14:15 IST",
        "route_color": "#3b82f6",
        "route_type": "HIGHWAY_NORTH_SH176",
        "state_of_origin": "Andhra Pradesh",
        "corridor_id": "CORRIDOR_NORTH_SH176",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-HR-26-4401",
        "license_plate": "HR-26-CX-4401",
        "carrier": "Haryana Express Freightlines",
        "driver_name": "Surender Yadav",
        "driver_phone": "+91 98120 77412",
        "driver_experience_years": 16,
        "truck_type": "MULTI_AXLE_40FT",
        "status": "INBOUND_HIGHWAY",
        "origin": "Manesar Auto Hub (Haryana) via NH-44",
        "destination": "MMLP Yard Block A",
        "cargo_name": "Precision CNC Castings & Fasteners",
        "cargo_type": "AUTO_PARTS",
        "container_no": "MSKU-992140-5",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 27.2,
        "tare_weight_tonnes": 4.0,
        "net_weight_tonnes": 23.2,
        "seal_number": "SL-HR-44019",
        "ewaybill_no": "EWB-2026-HR-440192",
        "latitude": 8.7845,
        "longitude": 78.1408,
        "heading": 176.0,
        "speed_kmh": 49.0,
        "fuel_or_battery_pct": 73.0,
        "eta_minutes": 14.0,
        "eta_timestamp": "14:22 IST",
        "route_color": "#3b82f6",
        "route_type": "HIGHWAY_NORTH_SH176",
        "state_of_origin": "Haryana",
        "corridor_id": "CORRIDOR_NORTH_SH176",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-TN-101",
        "license_plate": "TN-69-AA-8412",
        "carrier": "V.O.C. Port Logistics Express",
        "driver_name": "S. Murugesan",
        "driver_phone": "+91 94432 10987",
        "driver_experience_years": 14,
        "truck_type": "PRIME_MOVER_40FT",
        "status": "INBOUND_TRANSIT",
        "origin": "Madurai Industrial Corridor via SH-176",
        "destination": "MMLP Yard Block A (Dry Export Bay 4)",
        "cargo_name": "Automobile Engine Components (Hyundai Tier-1)",
        "cargo_type": "AUTO_PARTS",
        "container_no": "MSKU-849102-3",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 26.4,
        "tare_weight_tonnes": 3.9,
        "net_weight_tonnes": 22.5,
        "seal_number": "SL-991204",
        "ewaybill_no": "EWB-2026-9841-0192",
        "latitude": 8.7695,
        "longitude": 78.1388,
        "heading": 172.0,
        "speed_kmh": 38.0,
        "fuel_or_battery_pct": 88.0,
        "eta_minutes": 5.0,
        "eta_timestamp": "14:12 IST",
        "route_color": "#3b82f6",
        "route_type": "HIGHWAY_NORTH_SH176",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_NORTH_SH176",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },

    # Corridor 2: NH-38 / NH-744 West Arterial (Bengaluru, Kerala, Tirunelveli)
    {
        "id": "TRK-KA-01-4419",
        "license_plate": "KA-01-MJ-4419",
        "carrier": "Bengaluru High-Tech Freight Lines",
        "driver_name": "K. Venkatesh Gowda",
        "driver_phone": "+91 99801 33214",
        "driver_experience_years": 12,
        "truck_type": "PRIME_MOVER_AIR_SUSPENSION",
        "status": "INBOUND_HIGHWAY",
        "origin": "Electronic City (Bengaluru, Karnataka) via NH-38",
        "destination": "MMLP Central Warehouse WH-01",
        "cargo_name": "Precision Telecom & EV Battery Modules",
        "cargo_type": "ELECTRONICS",
        "container_no": "TCKU-662901-4",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 21.2,
        "tare_weight_tonnes": 3.9,
        "net_weight_tonnes": 17.3,
        "seal_number": "SL-KA-44102",
        "ewaybill_no": "EWB-2026-KA-441908",
        "latitude": 8.7745,
        "longitude": 78.1180,
        "heading": 128.0,
        "speed_kmh": 46.0,
        "fuel_or_battery_pct": 79.0,
        "eta_minutes": 8.5,
        "eta_timestamp": "14:16 IST",
        "route_color": "#eab308",
        "route_type": "HIGHWAY_WEST_NH38",
        "state_of_origin": "Karnataka",
        "corridor_id": "CORRIDOR_WEST_NH38",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-KL-07-3318",
        "license_plate": "KL-07-CD-3318",
        "carrier": "Malabar Coast Transshipment Carrier",
        "driver_name": "K. V. Mathew",
        "driver_phone": "+91 94470 12890",
        "driver_experience_years": 15,
        "truck_type": "PRIME_MOVER_40FT",
        "status": "INBOUND_HIGHWAY",
        "origin": "Kochi Cochin Port Corridor (Kerala) via NH-744",
        "destination": "MMLP Yard Block B (Spices Warehouse)",
        "cargo_name": "Malabar Black Pepper, Cardamom & Rubber Coir",
        "cargo_type": "AGRO_SPICES",
        "container_no": "SUDU-881290-6",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 24.2,
        "tare_weight_tonnes": 3.9,
        "net_weight_tonnes": 20.3,
        "seal_number": "SL-KL-77210",
        "ewaybill_no": "EWB-2026-KL-771290",
        "latitude": 8.7770,
        "longitude": 78.1120,
        "heading": 130.0,
        "speed_kmh": 44.0,
        "fuel_or_battery_pct": 71.0,
        "eta_minutes": 11.0,
        "eta_timestamp": "14:19 IST",
        "route_color": "#eab308",
        "route_type": "HIGHWAY_WEST_NH38",
        "state_of_origin": "Kerala",
        "corridor_id": "CORRIDOR_WEST_NH38",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-TS-09-5510",
        "license_plate": "TS-09-UB-5510",
        "carrier": "Deccan Fast Cargo Lines (Hyderabad)",
        "driver_name": "Mohd. Azharuddin",
        "driver_phone": "+91 98490 22184",
        "driver_experience_years": 13,
        "truck_type": "PRIME_MOVER_40FT",
        "status": "INBOUND_HIGHWAY",
        "origin": "HITEC City (Hyderabad, Telangana) via NH-44",
        "destination": "MMLP Yard Block A",
        "cargo_name": "Solar Inverters & Optical Transceivers",
        "cargo_type": "ELECTRONICS",
        "container_no": "HDMU-440192-3",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 20.5,
        "tare_weight_tonnes": 3.8,
        "net_weight_tonnes": 16.7,
        "seal_number": "SL-TS-99014",
        "ewaybill_no": "EWB-2026-TS-551092",
        "latitude": 8.7710,
        "longitude": 78.1230,
        "heading": 128.0,
        "speed_kmh": 45.0,
        "fuel_or_battery_pct": 76.0,
        "eta_minutes": 6.0,
        "eta_timestamp": "14:14 IST",
        "route_color": "#eab308",
        "route_type": "HIGHWAY_WEST_NH38",
        "state_of_origin": "Telangana",
        "corridor_id": "CORRIDOR_WEST_NH38",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },

    # Corridor 3: Port Access Expressway (VOC Port Wharf to MMLP Central Depot)
    {
        "id": "TRK-TN-105",
        "license_plate": "TN-69-C-5581",
        "carrier": "VOC Port Dedicated Feeder Shuttle",
        "driver_name": "K. Anbazhagan",
        "driver_phone": "+91 94421 99012",
        "driver_experience_years": 11,
        "truck_type": "PRIME_MOVER_40FT",
        "status": "INBOUND_TRANSIT",
        "origin": "VOC Port Berth 8 Container Wharf",
        "destination": "MMLP Central Warehouse WH-01",
        "cargo_name": "Imported Solar PV Inverters & Panels",
        "cargo_type": "GENERAL_CARGO",
        "container_no": "MSKU-109234-8",
        "iso_type": "40HC High-Cube",
        "gross_weight_tonnes": 22.4,
        "tare_weight_tonnes": 3.8,
        "net_weight_tonnes": 18.6,
        "seal_number": "SL-551982",
        "ewaybill_no": "EWB-2026-7781-5501",
        "latitude": 8.7580,
        "longitude": 78.1500,
        "heading": 285.0,
        "speed_kmh": 40.0,
        "fuel_or_battery_pct": 81.0,
        "eta_minutes": 5.0,
        "eta_timestamp": "14:12 IST",
        "route_color": "#10b981",
        "route_type": "PORT_ACCESS_EXPRESSWAY",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_PORT_EXPRESSWAY",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-TN-69-D-7734",
        "license_plate": "TN-69-D-7734",
        "carrier": "Pearl City Heavy Haulage",
        "driver_name": "V. Ganesan",
        "driver_phone": "+91 94433 11890",
        "driver_experience_years": 19,
        "truck_type": "SPECIALIZED_LOW_BED_CARRIER",
        "status": "PORT_TRANSIT",
        "origin": "VOC Port Coastal Heavy Berth 4",
        "destination": "MMLP Heavy Machinery Yard Block E",
        "cargo_name": "Wind Turbine Nacelle & Generator Assemblies",
        "cargo_type": "PROJECT_CARGO",
        "container_no": "OVERSIZE-WIND-09",
        "iso_type": "40FR Flat Rack",
        "gross_weight_tonnes": 42.0,
        "tare_weight_tonnes": 6.5,
        "net_weight_tonnes": 35.5,
        "seal_number": "SL-WIND-8812",
        "ewaybill_no": "EWB-2026-WIND-77341",
        "latitude": 8.7592,
        "longitude": 78.1460,
        "heading": 284.0,
        "speed_kmh": 32.0,
        "fuel_or_battery_pct": 86.0,
        "eta_minutes": 6.5,
        "eta_timestamp": "14:14 IST",
        "route_color": "#10b981",
        "route_type": "PORT_ACCESS_EXPRESSWAY",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_PORT_EXPRESSWAY",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },

    # Corridor 4: SIPCOT Industrial Chemical Bypass (Hazmat)
    {
        "id": "TRK-GJ-01-7722",
        "license_plate": "GJ-01-TX-7722",
        "carrier": "Gujarat Petrochem Freight Lines",
        "driver_name": "Dhaval M. Shah",
        "driver_phone": "+91 98980 66541",
        "driver_experience_years": 19,
        "truck_type": "HAZMAT_TANK_TRAILER",
        "status": "INBOUND_HIGHWAY",
        "origin": "Dahej Petrochemical SEZ (Gujarat) via NH-48/NH-44",
        "destination": "MMLP Yard Block D (Hazmat Isolation)",
        "cargo_name": "Specialty Polymer Resins & Monomers (Class 3)",
        "cargo_type": "CHEMICALS_FLAMMABLE",
        "container_no": "HLXU-990142-3",
        "iso_type": "20HZ Hazmat Tank",
        "gross_weight_tonnes": 23.4,
        "tare_weight_tonnes": 3.1,
        "net_weight_tonnes": 20.3,
        "seal_number": "SL-GJ-44910",
        "ewaybill_no": "EWB-2026-GJ-449120",
        "latitude": 8.7650,
        "longitude": 78.1340,
        "heading": 190.0,
        "speed_kmh": 35.0,
        "fuel_or_battery_pct": 77.0,
        "eta_minutes": 4.0,
        "eta_timestamp": "14:11 IST",
        "route_color": "#f97316",
        "route_type": "SIPCOT_HAZMAT_BYPASS",
        "state_of_origin": "Gujarat",
        "corridor_id": "CORRIDOR_SIPCOT_HAZMAT",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-TN-69-Z-1102",
        "license_plate": "TN-69-Z-1102",
        "carrier": "Southern Chemical Freight Trans",
        "driver_name": "M. Kumar",
        "driver_phone": "+91 99401 88234",
        "driver_experience_years": 16,
        "truck_type": "HAZMAT_CERTIFIED_PRIME_MOVER",
        "status": "YARD_STACKING",
        "origin": "SIPCOT Chemical Manufacturing Complex",
        "destination": "Yard Block D (Hazmat Isolation Bay 1)",
        "cargo_name": "Industrial Solvents (IMDG Class 3 Flammable)",
        "cargo_type": "CHEMICALS_FLAMMABLE",
        "container_no": "HLXU-402918-7",
        "iso_type": "20HZ Hazmat Tank Container",
        "gross_weight_tonnes": 19.8,
        "tare_weight_tonnes": 2.4,
        "net_weight_tonnes": 17.4,
        "seal_number": "SL-661902",
        "ewaybill_no": "EWB-2026-9931-6602",
        "latitude": 8.7622,
        "longitude": 78.1372,
        "heading": 90.0,
        "speed_kmh": 0.0,
        "fuel_or_battery_pct": 65.0,
        "eta_minutes": 0.0,
        "eta_timestamp": "At Stack (14:02 IST)",
        "route_color": "#f97316",
        "route_type": "SIPCOT_HAZMAT_BYPASS",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_SIPCOT_HAZMAT",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },

    # Corridor 5: South Coastal Logistics Highway (Reefer Cold-Chain & Sea Cargo)
    {
        "id": "TRK-TN-102",
        "license_plate": "TN-72-B-9923",
        "carrier": "Tuticorin Marine Cold Chain Logistics",
        "driver_name": "R. Vignesh",
        "driver_phone": "+91 98402 77651",
        "driver_experience_years": 8,
        "truck_type": "REEFER_CARRIER_40FT",
        "status": "WEIGHBRIDGE_MEASURING",
        "origin": "Tuticorin Fisheries Harbour Terminal",
        "destination": "Cold Chain Warehouse WH-02 / Yard Block C",
        "cargo_name": "Frozen Black Tiger Prawns (-18.5°C)",
        "cargo_type": "SEAFOOD_COLD_CHAIN",
        "container_no": "MAEU-310492-1",
        "iso_type": "40RF Reefer Container",
        "gross_weight_tonnes": 25.8,
        "tare_weight_tonnes": 4.5,
        "net_weight_tonnes": 21.3,
        "seal_number": "SL-884190",
        "ewaybill_no": "EWB-2026-4412-8819",
        "latitude": 8.7618,
        "longitude": 78.1370,
        "heading": 210.0,
        "speed_kmh": 0.0,
        "fuel_or_battery_pct": 74.0,
        "eta_minutes": 0.0,
        "eta_timestamp": "At Scale (14:05 IST)",
        "route_color": "#f43f5e",
        "route_type": "SOUTH_COASTAL_LOGISTICS",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_SOUTH_COASTAL",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },
    {
        "id": "TRK-TN-69-M-9021",
        "license_plate": "TN-69-M-9021",
        "carrier": "Gulf of Mannar Agro Transport",
        "driver_name": "P. Arumugam",
        "driver_phone": "+91 94431 88401",
        "driver_experience_years": 10,
        "truck_type": "PRIME_MOVER_40FT",
        "status": "INBOUND_TRANSIT",
        "origin": "Thoothukudi Salt Pans & Agro Processing Hub",
        "destination": "MMLP Yard Block B",
        "cargo_name": "Refined Industrial Grade Salt & Minerals",
        "cargo_type": "BULK_MINERALS",
        "container_no": "SUTU-660142-9",
        "iso_type": "20GP General Cargo",
        "gross_weight_tonnes": 21.6,
        "tare_weight_tonnes": 2.3,
        "net_weight_tonnes": 19.3,
        "seal_number": "SL-SALT-9912",
        "ewaybill_no": "EWB-2026-SALT-9021",
        "latitude": 8.7620,
        "longitude": 78.1385,
        "heading": 270.0,
        "speed_kmh": 28.0,
        "fuel_or_battery_pct": 89.0,
        "eta_minutes": 3.0,
        "eta_timestamp": "14:09 IST",
        "route_color": "#f43f5e",
        "route_type": "SOUTH_COASTAL_LOGISTICS",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_SOUTH_COASTAL",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    },

    # Terminal Internal Electric AGV
    {
        "id": "TRK-TN-103",
        "license_plate": "TN-69-X-4410",
        "carrier": "MMLP Autonomous Electric Fleet",
        "driver_name": "Autonomous AGV Unit 03",
        "driver_phone": "Control Room #4",
        "driver_experience_years": 0,
        "truck_type": "EV_TERMINAL_AGV",
        "status": "MOVING_TO_YARD",
        "origin": "Intermodal Rail Siding S1 (Track 1)",
        "destination": "Cross-Dock Hub WH-03 / Yard Block B",
        "cargo_name": "Export Cotton Textiles & Garments",
        "cargo_type": "TEXTILES_GARMENTS",
        "container_no": "CMAU-992104-5",
        "iso_type": "20GP General Cargo",
        "gross_weight_tonnes": 14.2,
        "tare_weight_tonnes": 2.2,
        "net_weight_tonnes": 12.0,
        "seal_number": "SL-772183",
        "ewaybill_no": "EWB-2026-1102-7721",
        "latitude": 8.7645,
        "longitude": 78.1365,
        "heading": 340.0,
        "speed_kmh": 22.0,
        "fuel_or_battery_pct": 92.0,
        "eta_minutes": 3.5,
        "eta_timestamp": "14:10 IST",
        "route_color": "#a855f7",
        "route_type": "INTERMODAL_RAIL_SHUTTLE",
        "state_of_origin": "Tamil Nadu",
        "corridor_id": "CORRIDOR_TERMINAL_AGV",
        "entity_type": "TRUCK",
        "data_source": "LIVE_TELEMETRY"
    }
]

INITIAL_VESSELS = [
    {
        "id": "SHP-VOC-801",
        "vessel_name": "MV MSC Thoothukudi Glory",
        "imo_number": "IMO 9841204",
        "call_sign": "9V8841",
        "flag": "Panama",
        "vessel_type": "ULTRA_LARGE_CONTAINER_VESSEL",
        "status": "APPROACHING_PORT_CHANNEL",
        "origin_port": "Port of Singapore (SGSIN)",
        "destination_port": "V.O. Chidambaranar Port (INVOY) - Berth 8",
        "cargo_description": "Solar PV Modules, Microelectronics & Heavy Machinery",
        "teu_capacity": 8500,
        "teu_onboard": 6420,
        "dwt_tonnes": 95000,
        "draft_meters": 13.8,
        "beam_meters": 42.0,
        "length_meters": 300.0,
        "speed_knots": 14.5,
        "speed_kmh": 26.8,
        "captain_name": "Capt. Aris Thorne",
        "pilot_onboard": True,
        "eta_timestamp": "15:30 IST (Today)",
        "latitude": 8.7400,
        "longitude": 78.2050,
        "heading": 298.0,
        "route_color": "#06b6d4",
        "entity_type": "VESSEL",
        "corridor_id": "CORRIDOR_GULF_OF_MANNAR_FAIRWAY",
        "data_source": "AIS_LIVE_STREAM"
    },
    {
        "id": "SHP-VOC-802",
        "vessel_name": "CMA CGM Colombo Feeder",
        "imo_number": "IMO 9711842",
        "call_sign": "9V4412",
        "flag": "Singapore",
        "vessel_type": "FEEDER_CONTAINER_SHIP",
        "status": "BERTHING_MANEUVER",
        "origin_port": "Port of Colombo (LKCMB)",
        "destination_port": "V.O. Chidambaranar Port (INVOY) - Berth 7",
        "cargo_description": "Apparel, Ceylon Tea, Seafood Reefers & Transshipment Cargo",
        "teu_capacity": 3200,
        "teu_onboard": 2840,
        "dwt_tonnes": 38000,
        "draft_meters": 11.2,
        "beam_meters": 30.0,
        "length_meters": 195.0,
        "speed_knots": 8.2,
        "speed_kmh": 15.2,
        "captain_name": "Capt. D. Samarasinghe",
        "pilot_onboard": True,
        "eta_timestamp": "14:45 IST (Berthing)",
        "latitude": 8.7475,
        "longitude": 78.1810,
        "heading": 305.0,
        "route_color": "#38bdf8",
        "entity_type": "VESSEL",
        "corridor_id": "CORRIDOR_PORT_INNER_BASIN",
        "data_source": "AIS_LIVE_STREAM"
    },
    {
        "id": "SHP-VOC-803",
        "vessel_name": "Maersk Arabian Pioneer",
        "imo_number": "IMO 9649912",
        "call_sign": "ZDF901",
        "flag": "Liberia",
        "vessel_type": "BULK_PETROCHEMICAL_CARRIER",
        "status": "INBOUND_SEA_LANE",
        "origin_port": "Jebel Ali Port (AEDXB, Dubai)",
        "destination_port": "VOC Port Liquid Jetty #2",
        "cargo_description": "Clean Petroleum Products & Industrial Monomers",
        "teu_capacity": 0,
        "teu_onboard": 0,
        "dwt_tonnes": 65000,
        "draft_meters": 12.5,
        "beam_meters": 38.0,
        "length_meters": 228.0,
        "speed_knots": 12.8,
        "speed_kmh": 23.7,
        "captain_name": "Capt. H. Lindholm",
        "pilot_onboard": False,
        "eta_timestamp": "17:15 IST (Today)",
        "latitude": 8.7320,
        "longitude": 78.2250,
        "heading": 292.0,
        "route_color": "#06b6d4",
        "entity_type": "VESSEL",
        "corridor_id": "CORRIDOR_GULF_OF_MANNAR_FAIRWAY",
        "data_source": "AIS_LIVE_STREAM"
    },
    {
        "id": "SHP-VOC-804",
        "vessel_name": "Evergreen Marine Pearl",
        "imo_number": "IMO 9812904",
        "call_sign": "BK4491",
        "flag": "Taiwan",
        "vessel_type": "POST_PANAMAX_CONTAINER_VESSEL",
        "status": "INBOUND_SEA_LANE",
        "origin_port": "Port Klang (MYPKG, Malaysia)",
        "destination_port": "VOC Port Berth 8 Container Wharf",
        "cargo_description": "Telecommunications Hardware, Batteries & Consumer Electronics",
        "teu_capacity": 6800,
        "teu_onboard": 5100,
        "dwt_tonnes": 80000,
        "draft_meters": 13.2,
        "beam_meters": 40.0,
        "length_meters": 285.0,
        "speed_knots": 13.6,
        "speed_kmh": 25.2,
        "captain_name": "Capt. Wei Chen",
        "pilot_onboard": False,
        "eta_timestamp": "16:20 IST (Today)",
        "latitude": 8.7280,
        "longitude": 78.2350,
        "heading": 296.0,
        "route_color": "#06b6d4",
        "entity_type": "VESSEL",
        "corridor_id": "CORRIDOR_GULF_OF_MANNAR_FAIRWAY",
        "data_source": "AIS_LIVE_STREAM"
    },
    {
        "id": "SHP-VOC-805",
        "vessel_name": "Tugboat VOC Viraat",
        "imo_number": "IMO 9401289",
        "call_sign": "ATV99",
        "flag": "India",
        "vessel_type": "HARBOUR_ASD_TUG",
        "status": "ESCORTING_VESSEL",
        "origin_port": "VOC Port Harbour Basin",
        "destination_port": "Berth 8 Approach Fairway",
        "cargo_description": "Harbour Pilotage & 70-Tonne Bollard Pull Towage",
        "teu_capacity": 0,
        "teu_onboard": 0,
        "dwt_tonnes": 450,
        "draft_meters": 5.2,
        "beam_meters": 11.5,
        "length_meters": 32.0,
        "speed_knots": 9.5,
        "speed_kmh": 17.6,
        "captain_name": "Capt. R. Soundararajan",
        "pilot_onboard": True,
        "eta_timestamp": "Active Operations",
        "latitude": 8.7505,
        "longitude": 78.1720,
        "heading": 115.0,
        "route_color": "#38bdf8",
        "entity_type": "VESSEL",
        "corridor_id": "CORRIDOR_PORT_INNER_BASIN",
        "data_source": "AIS_LIVE_STREAM"
    }
]

INITIAL_TRAINS = [
    {
        "id": "TRN-CONCOR-6641",
        "train_number": "CONCOR Super-Rake #66412",
        "loco_number": "WAG-9 Electric #31244 (6000 HP)",
        "operator": "Container Corporation of India (CONCOR)",
        "status": "APPROACHING_MMLP_SIDING",
        "origin_terminal": "Chennai Tondiarpet ICD (TN) via Southern Railway",
        "destination_terminal": "Thoothukudi MMLP Rail Hub (Track S1)",
        "total_wagons": 45,
        "total_teu": 90,
        "gross_train_weight_tonnes": 2480.0,
        "cargo_description": "Export Finished Automobiles, Granite Slabs & Textiles",
        "speed_kmh": 52.0,
        "loco_pilot_name": "K. Ravichandran",
        "assistant_pilot_name": "T. Balasubramanian",
        "eta_timestamp": "14:25 IST (Today)",
        "latitude": 8.7750,
        "longitude": 78.1310,
        "heading": 158.0,
        "route_color": "#a855f7",
        "corridor_id": "CORRIDOR_SOUTHERN_RAILWAY_MAINLINE",
        "entity_type": "TRAIN",
        "data_source": "FOIS_RAIL_TELEMETRY"
    },
    {
        "id": "TRN-SR-4402",
        "train_number": "Southern Railway Inland Shuttle #4402",
        "loco_number": "WDG-4 Dual Cab Diesel #12098 (4500 HP)",
        "operator": "Indian Railways (Southern Zone)",
        "status": "INBOUND_MAINLINE",
        "origin_terminal": "Bengaluru Whitefield ICD (Karnataka)",
        "destination_terminal": "VOC Port Rail Wharf Line 2",
        "total_wagons": 35,
        "total_teu": 70,
        "gross_train_weight_tonnes": 1920.0,
        "cargo_description": "Aerospace Forgings, Coffee Beans & Coir Fiber",
        "speed_kmh": 46.0,
        "loco_pilot_name": "A. Senthil Kumar",
        "assistant_pilot_name": "P. Suresh",
        "eta_timestamp": "14:40 IST (Today)",
        "latitude": 8.7850,
        "longitude": 78.1250,
        "heading": 152.0,
        "route_color": "#a855f7",
        "corridor_id": "CORRIDOR_SOUTHERN_RAILWAY_MAINLINE",
        "entity_type": "TRAIN",
        "data_source": "FOIS_RAIL_TELEMETRY"
    },
    {
        "id": "TRN-VOC-109",
        "train_number": "VOC Port Industrial Coal Hopper #109",
        "loco_number": "WAG-9 Electric #31802 (6000 HP)",
        "operator": "Indian Railways Freight Operations",
        "status": "PORT_RAIL_DISPATCH",
        "origin_terminal": "VOC Port Coal Wharf Siding",
        "destination_terminal": "Tuticorin Thermal Power & SIPCOT Industrial Siding",
        "total_wagons": 42,
        "total_teu": 84,
        "gross_train_weight_tonnes": 2650.0,
        "cargo_description": "High-Grade Metallurgical Coal & Thermal Energy Minerals",
        "speed_kmh": 36.0,
        "loco_pilot_name": "M. Duraisamy",
        "assistant_pilot_name": "R. Selvaraj",
        "eta_timestamp": "15:10 IST (Today)",
        "latitude": 8.7650,
        "longitude": 78.1480,
        "heading": 265.0,
        "route_color": "#c084fc",
        "corridor_id": "CORRIDOR_PORT_RAIL_SIDING",
        "entity_type": "TRAIN",
        "data_source": "FOIS_RAIL_TELEMETRY"
    }
]

INITIAL_CONTAINERS = [
    {
        "id": "SHP-VOC-801",
        "vessel_name": "MV MSC Thoothukudi Glory",
        "imo_number": "IMO 9841204",
        "call_sign": "9V8841",
        "flag": "Panama",
        "vessel_type": "ULTRA_LARGE_CONTAINER_VESSEL",
        "status": "APPROACHING_PORT_CHANNEL",
        "origin_port": "Port of Singapore (SGSIN)",
        "destination_port": "V.O. Chidambaranar Port (INVOY) - Berth 8",
        "cargo_description": "Solar PV Modules, Microelectronics & Heavy Machinery",
        "teu_capacity": 8500,
        "teu_onboard": 6420,
        "dwt_tonnes": 95000,
        "draft_meters": 13.8,
        "beam_meters": 42.0,
        "length_meters": 300.0,
        "speed_knots": 14.5,
        "speed_kmh": 26.8,
        "captain_name": "Capt. Aris Thorne",
        "pilot_onboard": True,
        "eta_timestamp": "15:30 IST (Today)",
        "latitude": 8.7400,
        "longitude": 78.2050,
        "heading": 298.0,
        "route_color": "#06b6d4",
        "entity_type": "VESSEL",
        "data_source": "AIS_LIVE_STREAM"
    },
    {
        "id": "SHP-VOC-802",
        "vessel_name": "CMA CGM Colombo Feeder",
        "imo_number": "IMO 9711842",
        "call_sign": "9V4412",
        "flag": "Singapore",
        "vessel_type": "FEEDER_CONTAINER_SHIP",
        "status": "BERTHING_MANEUVER",
        "origin_port": "Port of Colombo (LKCMB)",
        "destination_port": "V.O. Chidambaranar Port (INVOY) - Berth 7",
        "cargo_description": "Apparel, Ceylon Tea, Seafood Reefers & Transshipment Cargo",
        "teu_capacity": 3200,
        "teu_onboard": 2840,
        "dwt_tonnes": 38000,
        "draft_meters": 11.2,
        "beam_meters": 30.0,
        "length_meters": 195.0,
        "speed_knots": 8.2,
        "speed_kmh": 15.2,
        "captain_name": "Capt. D. Samarasinghe",
        "pilot_onboard": True,
        "eta_timestamp": "14:45 IST (Berthing)",
        "latitude": 8.7475,
        "longitude": 78.1810,
        "heading": 305.0,
        "route_color": "#38bdf8",
        "entity_type": "VESSEL",
        "data_source": "AIS_LIVE_STREAM"
    },
    {
        "id": "SHP-VOC-803",
        "vessel_name": "Maersk Arabian Pioneer",
        "imo_number": "IMO 9649912",
        "call_sign": "ZDF901",
        "flag": "Liberia",
        "vessel_type": "BULK_PETROCHEMICAL_CARRIER",
        "status": "INBOUND_SEA_LANE",
        "origin_port": "Jebel Ali Port (AEDXB, Dubai)",
        "destination_port": "VOC Port Liquid Jetty #2",
        "cargo_description": "Clean Petroleum Products & Industrial Monomers",
        "teu_capacity": 0,
        "teu_onboard": 0,
        "dwt_tonnes": 65000,
        "draft_meters": 12.5,
        "beam_meters": 38.0,
        "length_meters": 228.0,
        "speed_knots": 12.8,
        "speed_kmh": 23.7,
        "captain_name": "Capt. H. Lindholm",
        "pilot_onboard": False,
        "eta_timestamp": "17:15 IST (Today)",
        "latitude": 8.7320,
        "longitude": 78.2250,
        "heading": 292.0,
        "route_color": "#f59e0b",
        "entity_type": "VESSEL",
        "data_source": "AIS_LIVE_STREAM"
    }
]

INITIAL_TRAINS = [
    {
        "id": "TRN-CONCOR-6641",
        "train_number": "CONCOR Super-Rake #66412",
        "loco_number": "WAG-9 Electric #31244 (6000 HP)",
        "operator": "Container Corporation of India (CONCOR)",
        "status": "APPROACHING_MMLP_SIDING",
        "origin_terminal": "Chennai Tondiarpet ICD (TN) via Southern Railway",
        "destination_terminal": "Thoothukudi MMLP Rail Hub (Track S1)",
        "total_wagons": 45,
        "total_teu": 90,
        "gross_train_weight_tonnes": 2480.0,
        "cargo_description": "Export Finished Automobiles, Granite Slabs & Textiles",
        "speed_kmh": 52.0,
        "loco_pilot_name": "K. Ravichandran",
        "assistant_pilot_name": "T. Balasubramanian",
        "eta_timestamp": "14:25 IST (Today)",
        "latitude": 8.7750,
        "longitude": 78.1310,
        "heading": 158.0,
        "route_color": "#a855f7",
        "entity_type": "TRAIN",
        "data_source": "FOIS_RAIL_TELEMETRY"
    },
    {
        "id": "TRN-SR-4402",
        "train_number": "Southern Railway Inland Shuttle #4402",
        "loco_number": "WDG-4 Dual Cab Diesel #12098 (4500 HP)",
        "operator": "Indian Railways (Southern Zone)",
        "status": "INBOUND_MAINLINE",
        "origin_terminal": "Bengaluru Whitefield ICD (Karnataka)",
        "destination_terminal": "VOC Port Rail Wharf Line 2",
        "total_wagons": 35,
        "total_teu": 70,
        "gross_train_weight_tonnes": 1920.0,
        "cargo_description": "Aerospace Forgings, Coffee Beans & Coir Fiber",
        "speed_kmh": 46.0,
        "loco_pilot_name": "A. Senthil Kumar",
        "assistant_pilot_name": "P. Suresh",
        "eta_timestamp": "14:40 IST (Today)",
        "latitude": 8.7850,
        "longitude": 78.1250,
        "heading": 152.0,
        "route_color": "#c084fc",
        "entity_type": "TRAIN",
        "data_source": "FOIS_RAIL_TELEMETRY"
    }
]

INITIAL_CONTAINERS = [
    {
        "id": "CONT-TN-01",
        "container_no": "MSKU-849102-3",
        "iso_type": "40HC",
        "cargo_type": "AUTO_PARTS",
        "cargo_description": "Automobile Engine Components for Export",
        "gross_weight_tonnes": 26.4,
        "tare_weight_tonnes": 3.9,
        "seal_number": "SL-991204",
        "status": "LOADED_ON_TRUCK",
        "yard_block_id": "BLOCK_A",
        "bay": 4,
        "row": 2,
        "tier": 1,
        "assigned_truck_id": "TRK-TN-101",
        "dwell_hours": 0.0,
        "hazmat_class": None,
        "temperature_celsius": None
    },
    {
        "id": "CONT-TN-02",
        "container_no": "MAEU-310492-1",
        "iso_type": "40RF",
        "cargo_type": "SEAFOOD_COLD_CHAIN",
        "cargo_description": "Frozen Black Tiger Prawns (-18.5°C)",
        "gross_weight_tonnes": 25.8,
        "tare_weight_tonnes": 4.5,
        "seal_number": "SL-884190",
        "status": "GATE_INSPECTED",
        "yard_block_id": "BLOCK_C_REEFER",
        "bay": 2,
        "row": 1,
        "tier": 1,
        "assigned_truck_id": "TRK-TN-102",
        "dwell_hours": 1.2,
        "hazmat_class": None,
        "temperature_celsius": -18.5
    },
    {
        "id": "CONT-TN-03",
        "container_no": "CMAU-992104-5",
        "iso_type": "20GP",
        "cargo_type": "TEXTILES_GARMENTS",
        "cargo_description": "Export Cotton Knitwear and Garments",
        "gross_weight_tonnes": 14.2,
        "tare_weight_tonnes": 2.2,
        "seal_number": "SL-772183",
        "status": "AT_YARD_STACK",
        "yard_block_id": "BLOCK_B",
        "bay": 3,
        "row": 2,
        "tier": 2,
        "assigned_truck_id": None,
        "dwell_hours": 24.5,
        "hazmat_class": None,
        "temperature_celsius": None
    },
    {
        "id": "CONT-TN-04",
        "container_no": "HLXU-402918-7",
        "iso_type": "20HZ",
        "cargo_type": "CHEMICALS_FLAMMABLE",
        "cargo_description": "Industrial Solvents (Class 3 Flammable)",
        "gross_weight_tonnes": 19.8,
        "tare_weight_tonnes": 2.4,
        "seal_number": "SL-661902",
        "status": "AT_YARD_STACK",
        "yard_block_id": "BLOCK_D_HAZMAT",
        "bay": 1,
        "row": 1,
        "tier": 1,
        "assigned_truck_id": None,
        "dwell_hours": 8.6,
        "hazmat_class": "CLASS_3_FLAMMABLE",
        "temperature_celsius": None
    }
]

INITIAL_EQUIPMENT = [
    {
        "id": "EQ-RTG-01",
        "name": "RTG Gantry Crane 01 (Yard Block A)",
        "equipment_type": "RTG_CRANE",
        "latitude": 8.7621,
        "longitude": 78.1371,
        "heading": 90.0,
        "status": "LIFTING",
        "current_job_id": "JOB-MOUNT-CONT-04",
        "moves_completed_today": 48,
        "fuel_efficiency_teu_per_hr": 28.5
    },
    {
        "id": "EQ-RS-02",
        "name": "Reach Stacker 02 (Reefer Stacks)",
        "equipment_type": "REACH_STACKER",
        "latitude": 8.7619,
        "longitude": 78.1368,
        "heading": 45.0,
        "status": "IDLE",
        "current_job_id": None,
        "moves_completed_today": 36,
        "fuel_efficiency_teu_per_hr": 22.0
    },
    {
        "id": "EQ-RMG-03",
        "name": "RMG Rail Crane (Siding Track 1)",
        "equipment_type": "RMG_RAIL_CRANE",
        "latitude": 8.7635,
        "longitude": 78.1360,
        "heading": 180.0,
        "status": "MOVING",
        "current_job_id": "JOB-TRAIN-LOAD-RAKE-12",
        "moves_completed_today": 62,
        "fuel_efficiency_teu_per_hr": 34.0
    }
]

INITIAL_GATE_PASSES = [
    {
        "id": "GP-2026-001",
        "pass_number": "GP-TH-0921",
        "truck_plate": "TN-69-AA-8412",
        "container_id": "MSKU-849102-3",
        "driver_name": "S. Murugesan",
        "pass_type": "INBOUND_IMPORT",
        "appointment_window": "14:00 - 15:00 IST",
        "gate_lane_id": "GATE_LANE_01_ANPR",
        "status": "CHECKED_IN",
        "booked_weight_tonnes": 26.4,
        "measured_weight_tonnes": 26.42,
        "qr_token": "QR-PASS-TH-9841-01"
    },
    {
        "id": "GP-2026-002",
        "pass_number": "GP-TH-0922",
        "truck_plate": "TN-72-B-9923",
        "container_id": "MAEU-310492-1",
        "driver_name": "R. Vignesh",
        "pass_type": "INBOUND_COLD_CHAIN",
        "appointment_window": "14:30 - 15:30 IST",
        "gate_lane_id": "GATE_LANE_02_FASTTRACK",
        "status": "WEIGHBRIDGE_VERIFIED",
        "booked_weight_tonnes": 22.0,
        "measured_weight_tonnes": 25.8,
        "qr_token": "QR-PASS-TH-4412-02"
    }
]

trucks_store = list(INITIAL_TRUCKS)
vessels_store = list(INITIAL_VESSELS)
trains_store = list(INITIAL_TRAINS)
containers_store = list(INITIAL_CONTAINERS)
equipment_store = list(INITIAL_EQUIPMENT)
gate_passes_store = list(INITIAL_GATE_PASSES)


@router.get("/trucks")
def list_trucks(status: Optional[str] = None):
    if status:
        return [t for t in trucks_store if t.get("status") == status]
    return trucks_store


@router.get("/trucks/{truck_id}")
def get_truck(truck_id: str):
    for t in trucks_store:
        if t["id"] == truck_id:
            return t
    raise HTTPException(status_code=404, detail="Truck not found")


@router.get("/vessels")
def list_vessels():
    return vessels_store


@router.get("/trains")
def list_trains():
    return trains_store


@router.get("/containers")
def list_containers(query: Optional[str] = None):
    if query:
        q = query.upper()
        return [c for c in containers_store if q in c.get("container_no", "") or q in c.get("cargo_type", "")]
    return containers_store


@router.get("/equipment")
def list_equipment():
    return equipment_store


@router.get("/gate-passes")
def list_gate_passes():
    return gate_passes_store


class NewGatePassRequest(BaseModel):
    truck_plate: str
    driver_name: str
    driver_phone: str
    container_no: str
    cargo_name: str
    cargo_type: str
    booked_weight_tonnes: float
    origin: str
    destination: str
    pass_type: str


@router.post("/gate-passes/generate")
def create_gate_pass(req: NewGatePassRequest):
    """Issues a new digital Gate Pass with automated QR Token and E-Waybill."""
    pass_id = f"GP-2026-{len(gate_passes_store) + 1:03d}"
    pass_num = f"GP-TH-{random.randint(1000, 9999)}"
    qr_token = f"QR-MMLP-{random.randint(100000, 999999)}"
    
    new_pass = {
        "id": pass_id,
        "pass_number": pass_num,
        "truck_plate": req.truck_plate.upper(),
        "container_id": req.container_no.upper(),
        "driver_name": req.driver_name,
        "driver_phone": req.driver_phone,
        "cargo_name": req.cargo_name,
        "cargo_type": req.cargo_type,
        "origin": req.origin,
        "destination": req.destination,
        "pass_type": req.pass_type,
        "appointment_window": f"{datetime.now().strftime('%H:%M')} - {(datetime.now() + timedelta(hours=1)).strftime('%H:%M')} IST",
        "gate_lane_id": "GATE_LANE_01_ANPR",
        "status": "ISSUED_SCHEDULED",
        "booked_weight_tonnes": req.booked_weight_tonnes,
        "measured_weight_tonnes": None,
        "qr_token": qr_token,
        "created_at": datetime.utcnow().isoformat() + "Z"
    }
    gate_passes_store.insert(0, new_pass)
    return {
        "status": "GATE_PASS_ISSUED",
        "gate_pass": new_pass
    }
